######################################
### CHANGE THE PARAMETERS IN THIS FILE
######################################

# Path of the images
path: './imageDataset/'

######################################
### Board details
######################################

# Sidelength of one chessboard sqaure in mm 
gridSize: 50.5
# Sidelength of the AruCo marker in mm 
arucoSize: 161.5
# What is the color of the checkerboard square in the bottom left corner?
bottomLeftField: 'white'
# Maximum number of vertical checkerboard corners of the target
gridMaxHeight: 9
# Maximum number of horizontal checkerboard corners of the target
gridMaxWidth: 11
# Number of checkerboard squares which are overlayed by the AruCo marker
aruCoHiddenSize: 4
# Selected AruCo dictionary
aruco_dict: 'aruco.DICT_3X3_1'

######################################
### Algorithm details
######################################

# Number of calibration runs
runs: 1000
# Number of selcted images per calibration run
numberOfImages: 15
# Criteria for findCornerSubPix
criteria:
  maxIter: 150
  diff: 0.25
# For every list entry, a calibration run is down
# Start with only the chessboard corners around the AruCo marker and end with every corner
# Then reduce the search radius sr to robustify the search
# If plot == True, the information of the images of 'plotList' will be shown
calibrations:
  - rows: 7
    columns: 7
    sr: 6
    plot: False
  - rows: 9
    columns: 11
    sr: 6
    plot: False
  - rows: 9
    columns: 11
    sr: 4
    plot: False
  - rows: 9
    columns: 11
    sr: 2
    plot: False
  - rows: 9
    columns: 11
    sr: 1
    plot: False

######################################
### Other
######################################

# Which images should be plotted (if 'plot' is set to true below) last
plotList: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 14]